### ISSUE TITLE
Link for extracted templates and reactions is dead

### ISSUE THREAD

**Issue by shaipranesh2** [connorcoley/rdchiral#33]
The link https://chemrxiv.org/articles/RDChiral_An_RDKit_Wrapper_for_Handling_Stereochemistry_in_Retrosynthetic_Template_Extraction_and_Application/7949024 which aims to redirect to extracted templates and reaction is dead. The link can be found in the readme of the page https://github.com/connorcoley/rdchiral/tree/master/templates.

**Comment by connorcoley** [comment]
Chemrxiv changed their links, now use https://chemrxiv.org/engage/chemrxiv/article-details/60c741240f50dbe270395a6d
