### ISSUE TITLE
how to deal with the multiple outcomes by 'rdchiralRun' from rdchiral/main.py?

### ISSUE THREAD

**Issue by queliyong** [connorcoley/rdchiral#35]
Hi,
After I extract a retrosynthesis template from a specific reaction, I use the product of this reaction and the rdchiralRun func to see if it can create the correct reactants of the reaction. But the outcomes show more than one result. Although I know each of them makes sense, only the one outcome is my desired result. How to eliminate the other undesired outcomes? thanks very much.

**Comment by connorcoley** [comment]
If the template can lead to multiple outcomes, there's really no way for the program to know what _your_ desired outcome is. Is there a way of modifying your template to be more specific? Or is there a post-processing step you can apply?

**Comment by queliyong** [comment]
> If the template can lead to multiple outcomes, there's really no way for the program to know what _your_ desired outcome is. Is there a way of modifying your template to be more specific? Or is there a post-processing step you can apply?

get it. Thanks for your illumerating reply.
