### ISSUE TITLE
does not work for reaction "CCC>>CC(O)C"

### ISSUE THREAD

**Issue by hongxianglics** [connorcoley/rdchiral#48]
Hi,

I am interested in this great tool and trying to extrat and apply the reaction templates. Recently there are many great work in C-H bond activation, whcih means it can change the C-H bond to C-OH and so on. I tried this simple reaction  "CCC>>CC(O)C" with the code in the figure below, and use the exactly same compound as the product to predict the precursor.
<img width="398" alt="rdchiral" src="https://github.com/connorcoley/rdchiral/assets/104338096/bdc53d2f-95cf-431b-ac9b-a9a74a7c6f89">
however, we can see in the outcome, the template can be extracted, but the precursor and not be predicted, the outcome list is just a empty list(last line)
<img width="850" alt="rdchiral result" src="https://github.com/connorcoley/rdchiral/assets/104338096/79979296-622d-49e0-835f-e7bff69d1f95">
when I try some simple reactions, such as oxidizing alcohol to aldehyde, it works well, but this reaction just does not work. I am really confused, could you please help me with it?

Best,

**Comment by hongxianglics** [comment]
solved, thanks!

**Comment by Reecy-Z** [comment]
> solved, thanks!

May I ask how you solved this problem?
